// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeusMed.DataAccess.Contexts;

#nullable disable

namespace ZeusMed.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230926062137_AvailableTimeTable")]
    partial class AvailableTimeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZeusMed.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId1")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId1");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.AvailableTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("AvailableTimes");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AssociatedServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedServiceId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.DoctorDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DoctorDetail");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.ServiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceDetail");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Appointment", b =>
                {
                    b.HasOne("ZeusMed.Core.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("ZeusMed.Core.Entities.Doctor", null)
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId1");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.AvailableTime", b =>
                {
                    b.HasOne("ZeusMed.Core.Entities.Doctor", "Doctor")
                        .WithMany("AvailableTimes")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Doctor", b =>
                {
                    b.HasOne("ZeusMed.Core.Entities.Service", "AssociatedService")
                        .WithMany("AssociatedDoctors")
                        .HasForeignKey("AssociatedServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssociatedService");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.DoctorDetail", b =>
                {
                    b.HasOne("ZeusMed.Core.Entities.Doctor", "Doctor")
                        .WithOne("DoctorDetail")
                        .HasForeignKey("ZeusMed.Core.Entities.DoctorDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.ServiceDetail", b =>
                {
                    b.HasOne("ZeusMed.Core.Entities.Service", "Service")
                        .WithOne("ServiceDetail")
                        .HasForeignKey("ZeusMed.Core.Entities.ServiceDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailableTimes");

                    b.Navigation("DoctorDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeusMed.Core.Entities.Service", b =>
                {
                    b.Navigation("AssociatedDoctors");

                    b.Navigation("ServiceDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
